### ISSUE TITLE
Fail when installing only with podfile

### ISSUE THREAD

**Issue by Titozzz** [SudoPlz/react-native-amplitude-analytics#11]
`#if __has_include(<React/RCTBridgeModule.h>)`
  `#import <React/RCTBridgeModule.h>`
  `#else`
  `#import "RCTBridgeModule.h"`
  `#endif`

This does not work properly, it only works if I change everything to 
`
#import <React/RCTBridgeModule.h>
`
because React/RCTBridgeModule.h does exist.
Maybe this is due to https://github.com/CocoaPods/CocoaPods/issues/2774

Do you have any idea ?

In the meantime, i'm using this postinstall script ...
    `"fix-RNAmplitude": "sed -i '' 's/#import \"RCTBridgeModule.h\"/#import <React\\/RCTBridgeModule.h>/' ./node_modules/react-native-amplitude-analytics/ios/AmplitudeSDK.h",`

**Comment by SudoPlz** [comment]
Merged.
