### ISSUE TITLE
Expanding upon installation instructions

### ISSUE THREAD

**Issue by gregjw** [SudoPlz/react-native-amplitude-analytics#15]
Could you expand upon 'add it to your project manually'?

Which directories would I put where?

**Comment by SudoPlz** [comment]
So this project has the react-native module part (which only needs a react-native link`) and then it needs the actual Amplitude SDK in order for it to work.

I've never manually integrated Amplitude SDK but they do have instructions [here](https://amplitude.zendesk.com/hc/en-us/articles/115002278527#installation).

You'll have to download the [source code](https://github.com/amplitude/Amplitude-iOS/archive/master.zip) manually as their help page says.

Why bother with all that and don't just use Cocoapods?

**Comment by lunatolun** [comment]
Using only CocoaPods does not work. You still have to do 
add files to project
add the RNAmplitudeSDK.xcodeproj from node_modules/react-native-amplitude-analytics/ios folder and add these two files: libRNAmplitudeSDK.a and libAmplitude-iOS.a to Linked Frameworks and Libraries under General tab.

It would be nice if you could update the readme

I tried both ways for iOS and none worked, until I did ^

installed to iOS via 
pod 'Amplitude-iOS', '~> 4.0.4'

**Comment by SudoPlz** [comment]
`react-native link` is crucial, I removed the extra clutter to make that obvious for people in the future.

**Comment by lunatolun** [comment]
@SudoPlz it did not work on my end. already tried. it says linked successfully but throws error. only doing ^ worked fine

**Comment by SudoPlz** [comment]
What error did it throw?

**Comment by lunatolun** [comment]
RNAmplitudeSDK: No native client found. Wrote the same info in the other issue

**Comment by SudoPlz** [comment]
I added more instructions in ReadMe. By the way you should not add `libAmplitude-iOS.a`  as that is handled by Cocoapods.
