### ISSUE TITLE
Carthage build fails.

### ISSUE THREAD

**Issue by dcoughlin** [SudoPlz/react-native-amplitude-analytics#16]
`"$(SRCROOT)/../../../ios/Carthage/Checkouts/Amplitude-iOS/Amplitude"`
needs to be added to the Header Search Paths just like the Pod directory already is:
`"$(SRCROOT)/../../../ios/Pods/Amplitude-iOS",`

Otherwise:  `"Amplitude.h"` and  `"AMPRevenue.h"` are not found when attempting to build target: **RNAmplitudeSDK**.

It must have worked because the build had a Pod install included as well already.  But on a straight Carthage build the ios/Pods directory will not exist and these header files cannot be found.

**Comment by SudoPlz** [comment]
Got it, I'm not super familiar with Carthage, as I prefer cocoa pods usually, but would you be kind enough to open a PR with that addition?

**Comment by dcoughlin** [comment]
Will do, thanks.
