### ISSUE TITLE
RNAmplitudeSDK: No native client found.

### ISSUE THREAD

**Issue by tavriaforever** [SudoPlz/react-native-amplitude-analytics#18]
react-native 0.54.2
nodejs 8.4.0

1. add line to pod 
```
# Uncomment the next line to define a global platform for your project
platform :ios, '8.0'

target 'atlantm' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
  pod 'Amplitude-iOS', '~> 4.0.4'
end

```

2. Install pods 
```
pod install
```

3. Build app
```
react-native run-ios
```

4. Add js code to app index.js
```
import RNAmplitute from 'react-native-amplitude-analytics';

console.log('RNAmplitute', RNAmplitute);

const amplitude = new RNAmplitute('....');

amplitude.logEvent('test event');
```

Get the error 
```
Unhandled JS Exception: RNAmplitudeSDK: No native client found. Is RNAmplitudeSDK installed in your native code project?
```

I tried to debug the problem and found that in index.js in react-native-amplitude-analytics – RNAmplitudeSDK is undefined. 

```
// Libraries
import { NativeModules, Platform } from 'react-native';

// Native Modules
const { RNAmplitudeSDK } = NativeModules;
var amplitudeHasInitialized = false;

console.log('RNAmplitudeSDK', RNAmplitudeSDK);

class Amplitude {
```

**Comment by SudoPlz** [comment]
Any react-native module will return undefined if you console log it, that doesn't mean much.

On the mean time did you `react-native link` at all?
It sounds to me that the react-native part of this module is not even linked to your iOS project.

Don't forget to `react-native link react-native-amplitude-analytics`

**Comment by lunatolun** [comment]
As @KELiON said, you still have to link the library (react-native link did not work for me)

For reference:
add files to project
add the RNAmplitudeSDK.xcodeproj from node_modules/react-native-amplitude-analytics/ios folder and add these two files: libRNAmplitudeSDK.a and libAmplitude-iOS.a to Linked Frameworks and Libraries under General tab.

It would be nice if you could update the readme

I tried both ways for iOS and none worked, until I did ^

installed to iOS via
pod 'Amplitude-iOS', '~> 4.0.4'
