### ISSUE TITLE
NPM package url problem

### ISSUE THREAD

**Issue by itchingpixels** [SudoPlz/react-native-amplitude-analytics#2]
Hi!

In package.json, the URL key points to a different package, making anyone who doesn't refer to this repository by its correct url install a different package.

    "url": "git+https://github.com/SudoPlz/react-native-amplitude-sdk.git"

Is this intentional? I'm very confused :)

Thank you!

**Comment by SudoPlz** [comment]
Oh I just forgot to publish the repo to npm.

Published now under 0.1.6

Thanks for the heads up.
