### ISSUE TITLE
For version 0.1.16, build fails due to createJSModules being removed in RN 0.47

### ISSUE THREAD

**Issue by rodrigoalmeidaee** [SudoPlz/react-native-amplitude-analytics#22]
Hi there,

When linking this library against RN 0.55 we found errors due to this override:

https://github.com/SudoPlz/react-native-amplitude-analytics/blob/a652de83bafb61b9eee5fe6e4827be50e86781f3/android/src/main/java/com/sudoplz/reactnativeamplitudeanalytics/RNAmplitudeSDKPackage.java#L31

```
> Task :react-native-amplitude-analytics:compileReleaseJavaWithJavac
/Users/gk/geet/SGLearner/node_modules/react-native-amplitude-analytics/android/src/main/java/com/sudoplz/reactnativeamplitudeanalytics/RNAmplitudeSDKPackage.java:30: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /Users/gk/geet/SGLearner/node_modules/react-native-amplitude-analytics/android/src/main/java/com/sudoplz/reactnativeamplitudeanalytics/RNAmplitudeSDK.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
1 error
```

It seems that this method got removed in RN 0.47.2, by this commit:

https://github.com/facebook/react-native/commit/ce6fb337a146e6f261f2afb564aa19363774a7a8

Locally simply removing `createJSModules` worked for me. In terms of a proper fix, should we just get rid of the `@Override` (so that the lib still builds against older RN versions, but won't cause problems with newer RN versions)?

**Comment by SudoPlz** [comment]
Not sure if it will work without @Override but we can definitely try that, can you create a PR @rodrigoalmeidaee ? I'll totally merge that.

**Comment by rodrigoalmeidaee** [comment]
@SudoPlz actually the fix I proposed was already made (https://github.com/SudoPlz/react-native-amplitude-analytics/commit/ea6af67d5bc84781129463f61aaf00603104fe01), but between switching versions and trying to get around with issue #21 I think I ended up with a corrupt/stale node_modules directory. With a clean install it works.

Closing this as it is not an issue after all, sorry about that 🙈

**Comment by SudoPlz** [comment]
You're right I totally forgot about that 😆
