### ISSUE TITLE
New logo/icon

### ISSUE THREAD

**Issue by mansya** [SudoPlz/react-native-amplitude-analytics#29]
Hi, I am a graphic designer, I want to help others in graphic design.

After I reviewed your project, you have no logo on this project. Therefore I want to contribute to this project by creating a new logo / icon. what do you think?

**Comment by SudoPlz** [comment]
Sure, I'll be happy to accept a PR my friend.

**Comment by mansya** [comment]
Hai, Sorry for late. I have design logo for this project. what do you think ? do you like it ?

![react native amplitudo analityc](https://user-images.githubusercontent.com/33461607/42493528-900f7ca6-8447-11e8-98b0-51850bb16e28.png)

**Comment by SudoPlz** [comment]
Yep it's great!

**Comment by mansya** [comment]
I will do pull requests and upload all files today. please wait :-)

**Comment by SudoPlz** [comment]
Awesome

**Comment by mansya** [comment]
I have upload all file to this link.
https://drive.google.com/open?id=1qaP_xZOpDMOr38phiB1LkzCSwbga3Kwk

And I have sent you pull requests for you. please check.

**Comment by SudoPlz** [comment]
Thanks @mansya !!
