### ISSUE TITLE
'Amplitude.h' file not found

### ISSUE THREAD

**Issue by KlimczakM** [SudoPlz/react-native-amplitude-analytics#33]
I'm trying to integrate Amplitude into React Native app using this library. Android works fine although the iOS fails with error:

```
"(...)/node_modules/react-native-amplitude-analytics/ios/AmplitudeSDK.h:11:9: 'Amplitude.h' file not found

#import "Amplitude.h""
^
```

When I check this in the Xcode I can see AmplitudeSDK.h which refers to Amplitude.h which is missing. 

React Native version: 0.55.4

Steps I made:
1. yarn add react-native-amplitude-analytics 
2. react-native link react-native-amplitude-analytics
3. check if everything was added correctly

Is there anything I am missing?

**Comment by SudoPlz** [comment]
I'll be away for a week so I can't really help atm but it looks like you haven't installed the amplitude pod. Did you go through the pod installation process?

**Comment by pincheira** [comment]
Same thing here:
```
.../node_modules/react-native-amplitude-analytics/ios/AmplitudeSDK.h:11:9: fatal error: 'Amplitude.h' file not found
#import "Amplitude.h"
        ^~~~~~~~~~~~~
1 error generated.
```

Any ideas?

cc/@KlimczakM @SudoPlz

**Comment by SudoPlz** [comment]
Did you go through the pod installation process (step 2 of the guide) as well?

**Comment by pincheira** [comment]
@SudoPlz didn't want to put cocoapods, too much for my little project.

So I fixed it for now:

I had to explicitly set:

```
"$(SRCROOT)/../../../ios/standupsmobile/Amplitude-iOS/Amplitude"
```

Under `Header Search Paths` within the project `RNAmplitudeSDK`

**Comment by SudoPlz** [comment]
Right yes that makes sense.

**Comment by pincheira** [comment]
@SudoPlz but gets overridden by `react-native link _libraryName_`.

Had to go the cocoapods way sadly, I also found out I need it for other libraries.

Thanks for taking the time to reply on a Saturday, and have a great one @SudoPlz

**Comment by pincheira** [comment]
So I just finished setting up cocoapods, the `Amplitude-iOS` pod installed well.

But within `react-native-amplitude-analytics/ios/AmplitudeSDK.h:11:9` it still cannot find the file? That's weird:

```
node_modules/react-native-amplitude-analytics/ios/AmplitudeSDK.h:11:9: fatal error: 'Amplitude.h' file not found
#import "Amplitude.h"
        ^~~~~~~~~~~~~
1 error generated.



** BUILD FAILED **
```

**Comment by SudoPlz** [comment]
I'm on vacation and can't take a deeper dive, but for done reason, the rn amplitude project can't find amplitude sdk files. Usually that's either because the sdk is not installed or most probably in your case because the header files of amplitude sdk are not exposed to the rn amplitude project.

That should not be a problem but it could be because you changed the header files manually.

Can you delete `node_modules/react-native-amplitude-analytics` and `yarn add react-native-amplitude-analytics`? That way a fresh copy of the rn amplitude project will be downloaded.

**Comment by KlimczakM** [comment]
I have resolved it. This instruction is incorrect:

> download the Amplitude-iOS sdk from here and add it to your project manually. Make sure the Amplitude-iOS directory of the SDK is included in the root of your app's ios folder.

Correct steps:
1. Download the Amplitude SDK from here: https://github.com/amplitude/Amplitude-iOS/archive/master.zip.
2. Extract the ZIP file.
3. Open extracted folder, **copy only Amplitude folder** (not whole unziped Amplitude-iOS!) **to your project `/ios/Pods` folder** (not the root `/ios`!), even if you don't use Pods (this location is expected by linked project).
4. **Rename copied Amplitude folder to Amplitude-iOS** (this is name expected by linked project).

**Comment by SudoPlz** [comment]
Interesting, what you said sounds right, and it looks like an extra header path should be added to the `react-native-amplitude-analytics`, so that it looks for headers inside `root/ios/Amplitude-iOS`.
Would it be too much to ask for that PR @KlimczakM ?
