### ISSUE TITLE
NPM install / setUserPropertyOnce is not a function

### ISSUE THREAD

**Issue by clementinoux** [SudoPlz/react-native-amplitude-analytics#34]
Hi, 

Thanks for the lib'.
Just for info, the installation by npm does not deliver (a priori) the latest version of the library code.

Indeed, the following function is not available despite the merge of PR #32 :

// set the user property once
amplitude.setUserPropertyOnce (property, value)

Cheers

**Comment by SudoPlz** [comment]
Whoops, let me take care of that.

**Comment by SudoPlz** [comment]
Try again with 0.1.19
