### ISSUE TITLE
Updating Amplitude SDK to 4.3.1 ?

### ISSUE THREAD

**Issue by tgensol** [SudoPlz/react-native-amplitude-analytics#37]
Hi there,

I was just wondering if it was possible to update the iOS SDK to the latest one (4.3.1). Th 4.0.4 will be soon one year old (October 2017),

Thanks,
Best regards

**Comment by SudoPlz** [comment]
Sure, would you like to submit a PR?

**Comment by SudoPlz** [comment]
Published in 0.2.*
