### ISSUE TITLE
Build Failed in Android

### ISSUE THREAD

**Issue by izabelavmelo** [SudoPlz/react-native-amplitude-analytics#4]
I did everything according to the documentation for configure react-native-amplitude-analytics. But my build failed in Android:

`.../MainApplication.java:64: error: constructor RNAmplitudeSDKPackage in class RNAmplitudeSDKPackage cannot be applied to given types;`
`          new RNAmplitudeSDKPackage(),`
`          ^`
`  required: Application`
`  found: no arguments`
`  reason: actual and formal argument lists differ in length`

I need to put `MainApplication.this` in `new RNAmplitudeSDKPackage(MainApplication.this),` at MainApplication.java

I`m adding this question here in case anyone has the same problem.

**Comment by mieszko4** [comment]
thanx, I had the same problem and this worked for me
