### ISSUE TITLE
Add append and prepend methods

### ISSUE THREAD

**Issue by StevenMasini** [SudoPlz/react-native-amplitude-analytics#42]
Hi @SudoPlz,

First thank you for providing this solution.

Would it be possible to add the method `append` and `prepend` to the project.

See [Setting User Properties](https://amplitude.zendesk.com/hc/en-us/articles/115002278527#setting-user-properties) for details.

I don't think it would be hard to add, I can submit a PR if you don't have time for it.

**Comment by SudoPlz** [comment]
Hi @StevenMasini for sure, I'll be happy to accept your PR immediately if you make sure the methods you implement run on both OS's

:)

**Comment by SudoPlz** [comment]
Closing this since it's a feature request.

**Comment by LaVielle** [comment]
Hi, I'd like to have this feature too :)

**Comment by SudoPlz** [comment]
It's now available in `0.2.12`
