### ISSUE TITLE
Ошибка сборки кастомного presenter

### ISSUE THREAD

**Issue by JorikFat** [SudoPlz/react-native-amplitude-analytics#45]
Осваиваю эту библиотеку и пробую сделать кастомный Presenter
Presenter:
` 
    @InjectViewState
    public class MainPresenter extends MvpPresenter<MainView> {
    DbHandler dbHandler;

    public MainPresenter(DbHandler dbHandler) {
        this.dbHandler = dbHandler;
    }
`

Activity:

`
public class MainActivity extends MvpAppCompatActivity implements MainView {

    private Button timeStamp;
    private RecyclerView listTimestamp;
    private TimeStampAdapterRV adapterRV;
    private DbHandler dbHandler = new DbHandler(this);

    @InjectPresenter MainPresenter presenter;

    @ProvidePresenter
    MainPresenter createMainPresenter(DbHandler handler){
        return new MainPresenter(dbHandler);
    }
`

Получаю ошибку:
`error: method createMainPresenter in class MainActivity cannot be applied to given types;
required: DbHandler
found: no arguments
reason: actual and formal argument lists differ in length`

**Comment by SudoPlz** [comment]
I think you posted that in the wrong repo, this is a react-native amplitude repo.

**Comment by JorikFat** [comment]
sorry

**Comment by SudoPlz** [comment]
no problem
