### ISSUE TITLE
TypeScript typings

### ISSUE THREAD

**Issue by dozoisch** [SudoPlz/react-native-amplitude-analytics#47]
Hi!

I have a TS file definition for this component. Would you like me to PR it here as index.d.ts OR would you prefer I add it to [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped).

PR'ing it here makes it easier to keep it in sync since it's side by side, but I'll go with your preference.

**Comment by SudoPlz** [comment]
Please open a PR, I appreciate it thank you!
