### ISSUE TITLE
[iOS] Not finding Amplitude-iOS SDK when building with manual SDK

### ISSUE THREAD

**Issue by CapitanRedBeard** [SudoPlz/react-native-amplitude-analytics#49]
#### Env
```
    react-native-amplitude-analytics @ ^0.2.6
	XCode @ 10.1
	MacOS Mojave @ 10.14
```

#### Problem
The iOS app doesn't build without errors due to problems with the manually downloaded Amplitude-iOS SDK.

*Note:* Library is building and running fine on Android

#### Steps

So following the build instructions for iOS:
1. Installed `npm i react-native-amplitude-analytics --save` ✅
2. Linked libraries `react-native link react-native-amplitude-analytics ` ✅
3. Double check that **RNAmplitudeSDK.xcodeproj** is in *'Libraries'* and ** libRNAmplitudeSDK.a** is in *'Link Binary With Libraries'* ✅
4. Manually setup Amplitude SDK
	a. Downloaded the latest SDK [here](https://amplitude.zendesk.com/hc/en-us/articles/115002278527#installation).
	b. Unzip download, rename folder from `Amplitude-iOS-master` => `Amplitude-iOS`
	c. Move directory to the `<PROJ_ROOT>/ios` directory
5. Build App, observe the following error:
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_AMPIdentify", referenced from:
      objc-class-ref in libRNAmplitudeSDK.a(AmplitudeSDK.o)
  "_OBJC_CLASS_$_AMPRevenue", referenced from:
      objc-class-ref in libRNAmplitudeSDK.a(AmplitudeSDK.o)
  "_OBJC_CLASS_$_Amplitude", referenced from:
      objc-class-ref in libRNAmplitudeSDK.a(AmplitudeSDK.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

#### Thoughts

This error indicates that some of the defined structs, `AMPIdentify`, `AMPRevenue`, `Amplitude` can not be found within the **libRNAmplitudeSDK.a** file.
So this implies that the checked(✅) steps are all working as intended, it's the SDK that is not being found properly.

#### Things I've tried so far:

1. Using and renaming the downloaded `Amplitude-iOS-master/Amplitude` to `Amplitude-iOS` instead of the root downloaded directory.
2. Full cleaning everything, watchman delete + derived data delete + clean build folder + computer restart
3. Adding `$(PROJECT_DIR)/Amplitude-iOS` to my *'Framework Search Paths'*

@SudoPlz Have you gotten the manual installation to work? If so is there something special I need to do with my Amplitude-iOS directory?

**Comment by CapitanRedBeard** [comment]
Just tried using various SDK versions from [here](https://github.com/amplitude/Amplitude-iOS/releases).

Tried the one linked in the readme which downloaded as: **Amplitude-iOS-master**
Tried the 4.3.1 in the link above which downloaded as: **Amplitude-iOS-4.3.1**
Tried the 4.0.4 in the link above which downloaded as: **Amplitude-iOS-4.0.4**

All of these I tried unzipping and placing in the `<PROJ_ROOT>/ios` directory and renamed it to `Amplitude-iOS` and when that didn't work I also tried unzipping them and only moving the `Amplitude-iOS-4.3.1/Amplitude` directory to `<PROJ_ROOT>/ios` directory and renamed it to `Amplitude-iOS`.

All of these steps produce the same clang errors after carefully cleaning, removing watchmen, closing Xcode, deleting derived data and rebuilding the app in Xcode.

@SudoPlz Can you confirm what SDK version I should be using, and if I should be using that entire directory that is zipped or just certain files from it?

Thanks appreciate your maintenance on this repo.

**Comment by CapitanRedBeard** [comment]
I've gotten this working by utilizing Carthage to install this SDK. I know Carthage is not supported by the React Native team however it is a much more hands off dependency manager than CocoaPods and really doesn't get in your way during development.

Anyway for those who don't want to install via CocoaPods, can't get the manual installation working and want to try Carthage here are the rough steps:

0. Install the package `npm i react-native-amplitude-analytics --save`
0. Link the package `react-native link react-native-amplitude-analytics`
1. Install carthage on your machine/CI like [as documented here](https://github.com/Carthage/Carthage#installing-carthage)
2. Add a following `Cartfile` and `Cartfile.resolved` files:
```
// ios/Cartfile
github "amplitude/Amplitude-iOS" ~> 4.1
```
```
//ios/Cartfile.resolved
github "amplitude/Amplitude-iOS" "v4.1.0"
```
3. Run `carthage update` this will fetch the Amplitude SDK and put it in the Carthage directory (it might also update the amplitude SDK to the latest, no biggie)
4. Add an additional *Framework Search Paths*: `$(PROJECT_DIR)/Carthage/Build/iOS`
5. Add a new script to move the pulled in Amplitude SDK into the Frameworks directory.

Clean everything and re-run and you should be good or close to good. 
I'm not an iOS developer so this took me awhile but I think this makes sense, Carthage is used whenever you need to get the latest SDK and is closer to the manual installation than the CocoaPods installation which I prefer.

Also you can add the files generated from `carthage update` to `.gitignore` and just run `carthage update` everytime you build fresh similar to `node_modules` and `yarn`. 
However I prefer leave them unignored and to just check in the SDK and only run `carthage update` when I want to upgrade the library for whatever reason.

**Comment by SudoPlz** [comment]
Apologies for not being much help with that issue. I don't think it has anything to do with the Amplitude version, as I've used many versions (plus the latest one) in production, without issues.
It's probably cocoapods miss-configuration that made your life harder. I'm glad it worked out for you with Carthage.

**Comment by CapitanRedBeard** [comment]
@SudoPlz All good my man, hopefully will save someone else down the line some trouble.

Much thanks to you for maintaining this package, 🙏

**Comment by tyewang** [comment]
Thanks for posting this! I've come across the exact same issue, with the exact same details and this is super helpful.

**Comment by CapitanRedBeard** [comment]
@Ankarrr Referring to [step 8 in Quick Start here](https://github.com/Carthage/Carthage#quick-start).


Here is a picture of what my Run Script section looks like under *Build Phases*
<img width="961" alt="screen shot 2018-12-21 at 3 12 27 pm" src="https://user-images.githubusercontent.com/5445860/50367156-1c6eb880-0533-11e9-8ffd-8188ed7cf037.png">

**Comment by g-maximov** [comment]
Thanks, @CapitanRedBeard, you saved me!
I've spent almost all day trying to successfully build RN project with this lib included, and your method worked

**Comment by cloudnine-testscript** [comment]
Hi @CapitanRedBeard I am getting this error now Please help.

ld: framework not found Amplitude_iOS
clang: error: linker command failed with exit code 1 (use -v to see invocation)

warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.1.99. (in target 'RNAddCalendarEvent' from project 'RNAddCalendarEvent')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.1.99. (in target 'RNAmplitudeSDK' from project 'RNAmplitudeSDK')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.1.99. (in target 'RNVectorIcons' from project 'RNVectorIcons')
warning: The iOS Simulator deployment target 'IPHONEOS_DEPLOYMENT_TARGET' is set to 7.0, but the range of supported deployment target versions is 8.0 to 13.1.99. (in target 'RCTRestart' from project 'RCTRestart')
** BUILD FAILED **


The following build commands failed:
	Ld /Users/apple/Desktop/newCX-Detox/ios/build/Build/Products/Debug-iphonesimulator/newCX.app/newCX normal x86_64
(1 failure)
detox[93730] ERROR: [cli.js] Error: Command failed: xcodebuild -project ios/newCX.xcodeproj -scheme newCX -configuration Debug -sdk iphonesimulator -derivedDataPath ios/build
