### ISSUE TITLE
0.60.x problems on Android

### ISSUE THREAD

**Issue by iamacup** [SudoPlz/react-native-amplitude-analytics#53]
Hey there

I have been migrating my project over to RN 0.60.x and am having trouble with react-native-amplitude-analytics - the error i am seeing is:

```
AwesomeProject/android/app/build/generated/rncli/src/main/java/com/facebook/react/PackageList.java:51: error: constructor RNAmplitudeSDKPackage in class RNAmplitudeSDKPackage cannot be applied to given types;
      new RNAmplitudeSDKPackage()
      ^
  required: Application
  found: no arguments
  reason: actual and formal argument lists differ in length
1 error
```

Which you can replicate on a fresh project like this:

```
react-native init AwesomeProject
cd AwesomeProject
yarn add react-native-amplitude-analytics
react-native run-android
```

This is to do with the change to auto-linking combined with the new build process on Android but i am not familiar with how the `PackageList.java` file is generated by the new CLI stuff so can't create a pull request to fix.

Environment:

```
System:
    OS: macOS 10.14.5
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 1.36 GB / 16.00 GB
    Shell: 3.2.57 - /bin/bash
  Binaries:
    Node: 12.2.0 - /usr/local/bin/node
    Yarn: 1.15.2 - /usr/local/bin/yarn
    npm: 6.10.0 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 12.2, macOS 10.14, tvOS 12.2, watchOS 5.2
    Android SDK:
      API Levels: 23, 28
      Build Tools: 28.0.3
      System Images: android-28 | Intel x86 Atom_64, android-28 | Google APIs Intel x86 Atom, android-28 | Google Play Intel x86 Atom
  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5692245
    Xcode: 10.2.1/10E1001 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.8.6 => 16.8.6 
    react-native: 0.60.3 => 0.60.3 
  npmGlobalPackages:
    create-react-native-app: 1.0.0
    react-native-cli: 2.0.1
```

**WORKAROUND:**

In the meantime - the following is needed to workaround the issue:

1) Create a file called `react-native.config.js` in the root of the project (same place as package.json)
2) Put this into that file: `module.exports = { dependencies: { 'react-native-amplitude-analytics': { platforms: { android: undefined } } } };`

This will then let you use all the manual linking as currently documented in the readme.

**Comment by SudoPlz** [comment]
Interesting, I didn't have the time to go through the changes needed for RN 0.60 to work so far, so if you can't wait I'd appreciate a PR.
If you can wait I'll try to go through the changes and update this project later this month.

**Comment by SudoPlz** [comment]
https://github.com/SudoPlz/react-native-amplitude-analytics/pull/54
