### ISSUE TITLE
RNAmplitudeSDK.logRevenue was called with 3 arguments but expects 4 arguments

### ISSUE THREAD

**Issue by dinodsaurus** [SudoPlz/react-native-amplitude-analytics#6]
Thanks a lot for this great package, but today I got this error while logging revenue.
https://www.dropbox.com/s/vhnqd6wrlg42963/Screenshot%202017-10-13%2012.14.11.png?dl=0

**Comment by SudoPlz** [comment]
Can you try the master branch now and let me know if it's fixed for you?
If so I'll bump the version and release on npm.

**Comment by dinodsaurus** [comment]
It works, thanks for this quick fix! 👍

**Comment by SudoPlz** [comment]
Perfect!

**Comment by SudoPlz** [comment]
Fixed on version 0.1.8
