### ISSUE TITLE
Add setSessionId method

### ISSUE THREAD

**Issue by msquitieri** [SudoPlz/react-native-amplitude-analytics#60]
Is it possible to expose the setSessionId method?

**Comment by SudoPlz** [comment]
Hey there, if anyone cares to open a PR with that I'd be happy to merge it.

**Comment by msquitieri** [comment]
Thanks @SudoPlz, it turns out our use case only needed the `getSessionId` method exposed, which I have implemented in #61. Closing this issue.

**Comment by SudoPlz** [comment]
Live in 0.2.10
