### ISSUE TITLE
Raw SQL queries used for SQLLite database

### ISSUE THREAD

**Issue by tusharsarkar** [SudoPlz/react-native-amplitude-analytics#68]
## Issue
App uses SQLite Database and execute raw SQL query. Untrusted user input in raw SQL queries can cause SQL Injection. Also sensitive information should be encrypted and written to the database.

## Risk

A SQL injection attack involves integrating SQL commands into input data, mimicking the syntax of a predefined SQL command. A successful SQL injection attack allows the attacker to read or write to the database and possibly execute administrative commands, depending on the permissions granted by the server.

## Fix

Verify that the following best practices have been followed: - Untrusted inputs are type-checked and/or validated using a list of acceptable values. -Prepared statements with variable binding (i.e. parameterized queries) are used when performing database queries. If prepared statements are defined, user-supplied data and SQL code are automatically separated.

## Code 

On File com/amplitude/api/DatabaseHelper.java

```

public void onCreate(SQLiteDatabase sQLiteDatabase) { 
sQLiteDatabase.execSQL(CREATE_STORE_TABLE); 
sQLiteDatabase.execSQL(CREATE_LONG_STORE_TABLE);
sQLiteDatabase.execSQL(CREATE_EVENTS_TABLE);
sQLiteDatabase.execSQL(CREATE_IDENTIFYS_TABLE);
}
if (i == 1) {
sQLiteDatabase.execSQL(CREATE_STORE_TABLE); if (i2 <= 2) {
}
sQLiteDatabase.execSQL(CREATE_IDENTIFYS_TABLE); sQLiteDatabase.execSQL(CREATE_LONG_STORE_TABLE);
}

private void resetDatabase(SQLiteDatabase sQLiteDatabase) {
sQLiteDatabase.execSQL("DROP TABLE IF EXISTS store"); 
sQLiteDatabase.execSQL("DROP TABLE IF EXISTS long_store");
sQLiteDatabase.execSQL("DROP TABLE IF EXISTS events");
sQLiteDatabase.execSQL("DROP TABLE IF EXISTS identifys");
onCreate(sQLiteDatabase);

```

**Comment by SudoPlz** [comment]
@tusharsarkar this is a react-native wrapper, I think maybe you meant to open this issue to some other repo?
