### ISSUE TITLE
SetUserId with null should remove user id, instead of crashing

### ISSUE THREAD

**Issue by Titozzz** [SudoPlz/react-native-amplitude-analytics#7]
Potential fixes : Don't use .toString on userID, or check if userID !== null

**Comment by Titozzz** [comment]
Thank you !

**Comment by Titozzz** [comment]
Can you release to NPM 👍 ?

**Comment by SudoPlz** [comment]
All set @Titozzz  :)

**Comment by Titozzz** [comment]
Thanks, my team put some stars on the repo so that people start using it more 😄

**Comment by SudoPlz** [comment]
Thanks man!
